# Generated by Django 5.2.1 on 2025-05-29 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('ninea', models.CharField(default='EMP001', max_length=20)),
                ('emp_name', models.CharField(max_length=50)),
                ('designation', models.CharField(default='Software Design', max_length=50)),
                ('emp_dob', models.DateField()),
                ('emp_gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1)),
            ],
        ),
    ]
